### ISSUE TITLE
`it is undefined behavior to use this value` error on latest nightly compiler

### ISSUE THREAD

**Issue by doonv** [Smithay/wayland-rs#698] opened 2024-02-11 15:35 UTC
Building on the latest nightly compiler (rustc 1.78.0-nightly (6cc484351 2024-02-10)) causes the following error:

```
   Compiling wayland-client v0.31.2
error[E0080]: it is undefined behavior to use this value
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[1].child_interface.<enum-variant(Some)>.0.<deref>.c_ptr.<enum-variant(Some)>.0: encountered reference to mutable memory in `const`
    |
    = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
    = note: the raw bytes of the constant (size: 8, align: 8) {
                ╾───alloc2328<imm>────╼                         │ ╾──────╼
            }
    = note: this error originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this note originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0080]: it is undefined behavior to use this value
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[1].child_interface.<enum-variant(Some)>.0.<deref>.c_ptr.<enum-variant(Some)>.0: encountered reference to mutable memory in `const`
    |
    = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
    = note: the raw bytes of the constant (size: 8, align: 8) {
                ╾───alloc2418<imm>────╼                         │ ╾──────╼
            }
    = note: this error originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0080]: it is undefined behavior to use this value
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[0].child_interface.<enum-variant(Some)>.0.<deref>.c_ptr.<enum-variant(Some)>.0: encountered reference to mutable memory in `const`
    |
    = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
    = note: the raw bytes of the constant (size: 8, align: 8) {
                ╾───alloc2484<imm>────╼                         │ ╾──────╼
            }
    = note: this error originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0080]: it is undefined behavior to use this value
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[1].arg_interfaces.<deref>[0].<deref>.c_ptr.<enum-variant(Some)>.0: encountered reference to mutable memory in `const`
    |
    = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
    = note: the raw bytes of the constant (size: 8, align: 8) {
                ╾───alloc2719<imm>────╼                         │ ╾──────╼
            }
    = note: this error originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0080]: it is undefined behavior to use this value
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[5].arg_interfaces.<deref>[0].<deref>.c_ptr.<enum-variant(Some)>.0: encountered reference to mutable memory in `const`
    |
    = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
    = note: the raw bytes of the constant (size: 8, align: 8) {
                ╾───alloc2930<imm>────╼                         │ ╾──────╼
            }
    = note: this error originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0080]: it is undefined behavior to use this value
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/lib.rs:218:9
    |
218 |         wayland_scanner::generate_interfaces!("wayland.xml");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[7].arg_interfaces.<deref>[0].<deref>.c_ptr.<enum-variant(Some)>.0: encountered reference to mutable memory in `const`
    |
    = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
    = note: the raw bytes of the constant (size: 8, align: 8) {
                ╾───alloc3042<imm>────╼                         │ ╾──────╼
            }
    = note: this error originates in the macro `wayland_scanner::generate_interfaces` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by alufers** [comment] 2024-02-11 19:37
I've bisected the nightly releases, and found the change which causes this error:

searched nightlies: from nightly-2024-02-09 to nightly-2024-02-11
regressed nightly: nightly-2024-02-11
searched commit range: https://github.com/rust-lang/rust/compare/d44e3b95cb9d410d89cb8ab3233906a33f43756a...6cc4843512d613f51ec81aba689180c31b0b28b6
regressed commit: https://github.com/rust-lang/rust/commit/6cc4843512d613f51ec81aba689180c31b0b28b6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 
```
</details>

**Comment by PolyMeilex** [comment] 2024-02-12 03:55
Looks like rustc is not happy about a ref to a mutable static here:
```rs
        pub static WL_CALLBACK_INTERFACE: wayland_backend::protocol::Interface =
            wayland_backend::protocol::Interface {
                name: "wl_callback",
                version: 1u32,
                requests: &[],
                events: &[wayland_backend::protocol::MessageDesc {
                    name: "done",
                    signature: &[wayland_backend::protocol::ArgumentType::Uint],
                    since: 1u32,
                    is_destructor: true,
                    child_interface: None,
                    arg_interfaces: &[],
                }],
                // This causes the error
                c_ptr: Some(unsafe { &wl_callback_interface }),
            };
        pub static mut wl_callback_interface: wayland_backend::protocol::wl_interface =
            wayland_backend::protocol::wl_interface {
                name: b"wl_callback\x00" as *const u8 as *const std::os::raw::c_char,
                version: 1,
                request_count: 0,
                requests: NULLPTR as *const wayland_backend::protocol::wl_message,
                event_count: 1,
                events: unsafe { &wl_callback_events as *const _ },
            };
```

Not sure why this static needs to be mutable yet.

**Comment by elinorbgr** [comment] 2024-02-12 08:14
The fact that the error is ``encountered reference to mutable memory in `const` `` makes me wonder if rustc is not trying to do some const-promotion in the definition of the static, and causing the whole thing to fail. I'll try to make a minimal example.

**Comment by elinorbgr** [comment] 2024-02-12 08:28
The issue you pointed @PolyMeilex seems to have been reported already as https://github.com/rust-lang/rust/issues/120949 and apparently has a coming fix https://github.com/rust-lang/rust/pull/120960 .

The reason we have `static mut` here is IIRC historical, because it was the only way to have rustc accept the generation of cyclic graph of pointers for use by libwayland. It's possible that it's no longer needed, I suggest we wait for a next nightly with that fix and see what we can do from that.

**Comment by RalfJung** [comment] 2024-02-12 10:22
> The fact that the error is encountered reference to mutable memory in `const` makes me wonder if rustc is not trying to do some const-promotion in the definition of the static, and causing the whole thing to fail. I'll try to make a minimal example.

What's happening is that the checks for whether `const`s and `static`s have a valid value have been tightened. Here you have a `'static` shared reference to a mutable static; if anyone ever mutates that static, then reading this reference is UB. In fact references to `static mut` are basically never a good idea due to this; such global mutable state should only be touched with raw pointers.

The cycle error should be fixed soon, but this UB check is remaining.

Though it is strange that it says "in `const`" when in your snippet, the reference is created in a `static`. And if I take your code into playground [it does not error on current nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=96e754c434325f328ae3464e84e5f255). Are you sure your snippet reflects what happens?

**Comment by elinorbgr** [comment] 2024-02-12 10:49
@RalfJung I think the problem with the code extract is that it was missing a level of indirection. This example does reproduce the issue: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b12b75e175cc0fc7ca186ed0e2ec869f

Now, as I wrote earlier, it is indeed entirely possible that the use of `static mut` is no longer needed. All those statics are not intended to be mutated ever. But given it is a bunch of statics containing raw pointers to other statics, previously rustc refused this code if I didn't make the statics `mut`. But last time I checked this was probably a few years ago, so I plan to check how it fares now.

**Comment by RalfJung** [comment] 2024-02-12 11:13
> I think the problem with the code extract is that it was missing a level of indirection. This example does reproduce the issue: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b12b75e175cc0fc7ca186ed0e2ec869f

Ah! Yes there we have `&[&WL_CALLBACK_INTERFACE]` which is a promoted.
https://github.com/rust-lang/rust/pull/120960 should fix this code then, since it takes back the change where statics mentioned inside promoteds get validated recursively. This is an interesting testcase, we should add it to rustc. (I don't know if we necessarily want to endorse this as correct code; the point of the testcase would be to make us aware when we change its behavior.)

> Now, as I wrote earlier, it is indeed entirely possible that the use of static mut is no longer needed. All those statics are not intended to be mutated ever. But given it is a bunch of statics containing raw pointers to other statics, previously rustc refused this code if I didn't make the statics mut. But last time I checked this was probably a few years ago, so I plan to check how it fares now.

Interesting. I'm not aware of how adding a `mut` would fix things if you don't plan to mutate anything. But we do relax some safety checks around `static mut` since they are horribly unsafe anyway, it's possible there are some surprising interactions here.

If `static mut` is still required, I'd be interested in seeing the example which demonstrates why `static` does not work.

**Comment by ids1024** [comment] 2024-02-12 19:53
`static mut` seems to be avoidable here. Not sure if it was needed for anything else in the past, but it seems to be only needed to use a non-`Sync` (i.e. types containing pointers) type in the static: https://github.com/Smithay/wayland-rs/pull/700

Though CI passing there will require a nightly that fixes the "cycle detected when const-evaluating " issue, I guess.

**Comment by RalfJung** [comment] 2024-02-12 20:02
Okay, good to know. :)

The fix landed, so a nightly with the fix should be released in a few hours.

**Comment by nvzqz** [comment] 2024-02-13 19:53
This seems to be fixed as of `nightly-2024-02-13`.

**Comment by ids1024** [comment] 2024-02-13 19:59
Yeah, I think we can close this now.

https://github.com/Smithay/wayland-rs/pull/700 should be a bit better of a way to do things, but not make any difference in behavior baring compiler bugs.

**Closed by ids1024** 2024-02-13 19:59 UTC
