### ISSUE TITLE
Backend+client API to take control of proxies

### ISSUE THREAD

**Issue by elinorbgr** [Smithay/wayland-rs#730] opened 2024-05-19 10:06 UTC
In some cases of FFI interaction, the user may be given a `*mut wl_proxy` that has not been initialized and is not managed by whatever created it. For such cases, the backend needs an API for taking control of such a `*mut wl_proxy`, and then some convenience methods should be added to client as well to integrate the newly initialized object into the event queue.

**Comment by chrisduerr** [comment] 2024-05-22 22:48
Could you provide some detail on how you'd imagine this to be implemented? I'm unfamiliar with wayland-rs but seems like this shouldn't be too rough.

**Comment by chrisduerr** [comment] 2024-05-30 21:33
This managed to successfully resolve my issues with my browser crashing due to leaked buffers:
https://github.com/catacombing/kumo/commit/1f99d2d40f743db45a30e9c05388f608cfc05193

I'd appreciate feedback on the implementation, I'm not sure if cloning the connection is the "correct" way to call destructors inside `ObjectData::event`?

If this gets merged, I'd also appreciate a 0.3.4 release with this in it, since I'd like to avoid running a patch version for an extended period of time since it can cause troubles with bisection.

**Comment by chrisduerr** [comment] 2024-07-22 20:09
#731 implemented everything I needed, so I think this can be closed?

I'll open a separate issue for the regression that broke this.

**Closed** 2024-07-29 09:50 UTC
