### ISSUE TITLE
Panic in adapted simple_window example when using use_system_lib feature.

### ISSUE THREAD

**Issue by mforsb** [Smithay/wayland-rs#278] opened 2019-10-26 20:37 UTC
I changed the simple_window example to use xdg_shell instead of wl_shell ([code](https://gist.github.com/mforsb/aea2f605064489449a8510189e4c5002)).

It works as expected when `use_system_lib` is not set, but when it is, the program panics with the message `Attemping to create an object from a non-attached proxy`. ([stderr with `RUST_BACKTRACE=full` and `WAYLAND_DEBUG=1`](https://gist.github.com/mforsb/2642b715325189445def97d07ce34e94).

It's entirely possible that I'm doing something bad, but I'd expect the program to work the same way whether `use_system_lib` is set or not.

System info:
`Fedora 30`
`gnome 3.32.2` or `sway 1.2-rc1-48-ga085e649`
`rustc 1.38.0 (625451e37 2019-09-23)`
`libwayland-client 1.17.0`
`wayland-client (rust) 0.24.0`

**Comment by vberger** [comment] 2019-10-27 18:26
Indeed, the `use_system_lib` feature should not change the behavior, so there is definitely a bug in `wayland-client`.

Your code looks correct, so I suspect the issue is with the code using the system lib.

**Comment by mforsb** [comment] 2019-10-27 21:33
If I remove [this check](https://github.com/Smithay/wayland-rs/blob/0aae9e856f0fab071077477ba2c6986e8ffbb721/wayland-client/src/native_lib/proxy.rs#L124) the program works as expected, but the `proxy_create_unattached` test fails.
I'm still receiving events on the `WlSeat` object, which I wouldn't expect to be the case if it truly was non-attached (assuming it refers to not being attached to an event queue).

It also seems weird to have an `is_none` check and then use [`unwrap_or`](https://github.com/Smithay/wayland-rs/blob/0aae9e856f0fab071077477ba2c6986e8ffbb721/wayland-client/src/native_lib/proxy.rs#L136) right after.

**Comment by vberger** [comment] 2019-10-31 11:39
In wayland-client's wording, "attached" does not refer to the wayland object, but to the proxy (handle to the object). An object is always assigned to an event queue on creation, and this assignation can never change. However, when a proxy is attached to an event queue, this makes new objects created by this proxy to be assigned on this event queue. This is why methods that create new objects can only be called on `AttachedProxy` (or `MainProxy`, which counts as attached to the same event queue as the underlying object is assigned).

The check you identified, ensures that creating an object is never attempted from a non-attached proxy (as the newly created object wold not be assigned to any event queue). However, there appears to be an issue in the code tracking which event queue a proxy is attached to, making it believe it is not attached while it should be.

I suspect I messed things up in the tracking of invariants, and the `unwrap_or` you spotted is a hint of that. An attached proxy with the C libwayland backend should have `self.wrapping` set to `Some(..)` if it is attached, and to `None` otherwise.

**Closed** 2019-11-02 19:00 UTC
Labels: crate: client, status: needs investigation, type: bug

**Comment by nifker** [comment] 2019-12-30 14:46
When I do an event_queue sync_roundtrip() after I attach the buffer I get "[wayland-client] Protocol error 3 on object xdg_surface@9: xdg_surface has never been configured"
https://paste.gg/p/anonymous/8b18f797ec224a9baebfca6b75828e4e
